#!/bin/sh

opt=( dummy commonname )
nopt=${#opt[*]}
if [ $# -le `expr ${nopt} - 2` ]; then
    echo "USAGE: $0" ${opt[*]:1:${nopt}}
    echo $*
    exit
fi

num=1
while [ $num -le `expr ${nopt} - 1` ]; do
    eval ${opt[$num]}=$1
    shift 1
    num=`expr $num + 1`
done

for filexvg in $( ls ${commonname}*.xvg ) ; do 
    file=$( basename ${filexvg} .xvg); 
    awk '(($1 !~ /^(\#|\@)/) && ($1%100==0)){printf("%8.3f , %8.3f , %8.3f , %8.3f\n"),$1/1000,$2,$3,$4}' ${filexvg}  > ${file}.csv  ; 
done
