#!/bin/sh

RES=( dummy )
RES[1]=GLY
RES[2]=GLY
RES[3]=ALA
RES[4]=ALA
RES[5]=VAL
RES[6]=VAL
RES[7]=LEU
RES[8]=LEU
RES[9]=ILE
RES[10]=ILE
RES[11]=PRO
RES[12]=PRO

RES[13]=MET
RES[14]=MET
RES[15]=MET
RES[16]=CYS
RES[17]=CYS
RES[18]=CYS
RES[19]=CYX
RES[20]=CYX
RES[21]=CYM
RES[22]=CYM
RES[23]=SER
RES[24]=SER
RES[25]=SER
RES[26]=THR
RES[27]=THR
RES[28]=THR

RES[29]=ASN
RES[30]=ASN
RES[31]=ASN
RES[32]=ASH
RES[33]=ASH
RES[34]=ASH
RES[35]=GLN
RES[36]=GLN
RES[37]=GLN
RES[38]=GLH
RES[39]=GLH
RES[40]=GLH
RES[41]=ASP
RES[42]=ASP
RES[43]=GLU
RES[44]=GLU

RES[45]=LYS
RES[46]=LYS
RES[47]=LYN
RES[48]=LYN
RES[49]=LYN
RES[50]=ARG
RES[51]=ARG
RES[52]=ARG
RES[53]=HIE
RES[54]=HIE
RES[55]=HIP
RES[56]=HIP
RES[57]=HID
RES[58]=HID

RES[59]=PHE
RES[60]=PHE
RES[61]=TY3
RES[62]=TY3
RES[63]=TY3
RES[64]=TRP
RES[65]=TRP

clustname=( dummy )
clustname[1]=Term_free           # GLY
clustname[2]=CH3_Term_fixed      # GLY
clustname[3]=Term_free           # ALA
clustname[4]=CH3_Term_fixed      # ALA
clustname[5]=Term_fixed          # VAL
clustname[6]=CH3_Term_fixed      # VAL
clustname[7]=Term_free           # LEU
clustname[8]=CH3_Term_fixed      # LEU
clustname[9]=Term_free           # ILE
clustname[10]=CH3_Term_fixed     # ILE
clustname[11]=Term_free          # PRO
clustname[12]=CH3_Term_fixed     # PRO

clustname[13]=Term_S_free          # MET
clustname[14]=Term_S_free_CH3_fixd # MET
clustname[15]=CH3_Term_fixed       # MET
clustname[16]=Term_free            # CYS
clustname[17]=CH3_Term_fixed       # CYS
clustname[18]=CH3_SH_Term_fixed    # CYS
clustname[19]=Term_free            # CYX
clustname[20]=CH3_OH_Term_fixed    # CYX
clustname[21]=Term_free            # CYM
clustname[22]=CH3_Term_fixed       # CYM
clustname[23]=Term_free            # SER
clustname[24]=CH3_Term_fixed       # SER
clustname[25]=CH3_OH_Term_fixed    # SER
clustname[26]=Term_free            # THR
clustname[27]=CH3_Term_fixed       # THR
clustname[28]=CH3_OH_Term_fixed    # THR

clustname[29]=Term_free          # ASN
clustname[30]=CH3_Term_fixed     # ASN
clustname[31]=CH3_NH2_Term_fixed # ASN
clustname[32]=Term_free          # ASH
clustname[33]=CH3_Term_fixed     # ASH
clustname[34]=CH3_OH_Term_fixed  # ASH
clustname[35]=Term_free          # GLN
clustname[36]=CH3_Term_fixed     # GLN
clustname[37]=CH3_NH2_Term_fixed # GLN
clustname[38]=Term_free          # GLH
clustname[39]=CH3_Term_fixed     # GLH
clustname[40]=CH3_OH_Term_fixed  # GLH
clustname[41]=Term_free          # ASP
clustname[42]=CH3_Term_fixed     # ASP
clustname[43]=Term_free          # GLU
clustname[44]=CH3_Term_fixed     # GLU

clustname[45]=Term_free            # LYS
clustname[46]=CH3_NH3_Term_fixed   # LYS
clustname[47]=Term_free            # LYM
clustname[48]=CH3_Term_fixed       # LYN
clustname[49]=CH3_NH2_Term_fixed   # LYN
clustname[50]=Term_C_free          # ARG
clustname[51]=Term_C_free_CH3_fixd # ARG
clustname[52]=CH3_NH2_Term_fixed   # ARG
clustname[53]=Term_free            # HIE
clustname[54]=CH3_Term_fixed       # HIE
clustname[55]=Term_free            # HIP
clustname[56]=CH3_Term_fixed       # HIP
clustname[57]=Term_free            # HID
clustname[58]=CH3_Term_fixed       # HID

clustname[59]=Term_free          # PHE
clustname[60]=CH3_NH3_Term_fixed # PHE
clustname[61]=Term_free          # TY3
clustname[62]=CH3_Term_fixed     # TY3
clustname[63]=CH3_OH_Term_fixed  # TY3
clustname[64]=Term_free          # TRP
clustname[65]=CH3_Term_fixed     # TRP

clt=( dummy )
clt[1]=~/calspa/input/dipep/GLYDv.clt
clt[2]=~/calspa/input/dipep/GLYDv_Term_fixed.clt
clt[3]=~/calspa/input/dipep/ALADv.clt
clt[4]=~/calspa/input/dipep/ALADv_CH3_Term_fixed.clt
clt[5]=~/calspa/input/dipep/ASPDv.clt
clt[6]=~/calspa/input/dipep/ASPDv_Term_fixed.clt
clt[7]=~/calspa/input/dipep/GLUDv.clt
clt[8]=~/calspa/input/dipep/GLUDv_Term_fixed.clt
clt[9]=~/calspa/input/dipep/LEUDv.clt
clt[10]=~/calspa/input/dipep/LEUDv_CH3_Term_fixed.clt
clt[11]=~/calspa/input/dipep/ILEDv.clt
clt[12]=~/calspa/input/dipep/ILEDv_CH3_Term_fixed.clt
clt[13]=~/calspa/input/dipep/ASNDv.clt
clt[14]=~/calspa/input/dipep/ASNDv_CH3_Term_fixed.clt
clt[15]=~/calspa/input/dipep/ASNDv_NH2_Term_fixed.clt
clt[16]=~/calspa/input/dipep/GLNDv.clt
clt[17]=~/calspa/input/dipep/GLNDv_CH3_Term_fixed.clt
clt[18]=~/calspa/input/dipep/GLNDv_NH2_Term_fixed.clt
clt[19]=~/calspa/input/dipep/VALDv.clt
clt[20]=~/calspa/input/dipep/VALDv_CH3_Term_fixed.clt
clt[21]=~/calspa/input/dipep/HIEDv.clt
clt[22]=~/calspa/input/dipep/HIEDv_Term_fixed.clt
clt[23]=~/calspa/input/dipep/SERDv.clt              
clt[24]=~/calspa/input/dipep/SERDv_Term_fixed.clt   
clt[25]=~/calspa/input/dipep/SERDv_OH_Term_fixed.clt
clt[26]=~/calspa/input/dipep/THRDv.clt
clt[27]=~/calspa/input/dipep/THRDv_CH3_Term_fixed.clt
clt[28]=~/calspa/input/dipep/THRDv_CH3_OH_Term_fixed.clt
clt[29]=~/calspa/input/dipep/METDv_S_free.clt
clt[30]=~/calspa/input/dipep/METDv_S_free_CH3_fixed.clt
clt[31]=~/calspa/input/dipep/METDv_Term_fixed.clt
clt[32]=~/calspa/input/dipep/CYSDv.clt 
clt[33]=~/calspa/input/dipep/CYSDv_CH3_Term_fixed.clt
clt[34]=~/calspa/input/dipep/CYSDv_SH_Term_fixed.clt
clt[35]=~/calspa/input/dipep/PRODv.clt 
clt[36]=~/calspa/input/dipep/PRODv_Term_fixed.clt
clt[37]=~/calspa/input/dipep/ARGDv_C_free.clt
clt[38]=~/calspa/input/dipep/ARGDv_C_free_CH3_fixed.clt
clt[39]=~/calspa/input/dipep/ARGDv_Term_fixed.clt
clt[40]=~/calspa/input/dipep/LYSDv.clt 
clt[41]=~/calspa/input/dipep/LYSDv_NH3_Term_fixed.clt
clt[42]=~/calspa/input/dipep/PHEDv.clt 
clt[43]=~/calspa/input/dipep/PHEDv_Term_fixed.clt
clt[44]=~/calspa/input/dipep/TY3Dv.clt 
clt[45]=~/calspa/input/dipep/TY3Dv_Term_fixed.clt
clt[46]=~/calspa/input/dipep/TY3Dv_OH_Term_fixed.clt
clt[47]=~/calspa/input/dipep/TRPDv.clt
clt[48]=~/calspa/input/dipep/TRPDv_Term_fixed.clt
clt[49]=~/calspa/input/dipep/ASHDv.clt 
clt[50]=~/calspa/input/dipep/ASHDv_Term_fixed.clt
clt[51]=~/calspa/input/dipep/ASHDv_OH_Term_fixed.clt
clt[52]=~/calspa/input/dipep/GLHDv.clt 
clt[53]=~/calspa/input/dipep/GLHDv_Term_fixed.clt
clt[54]=~/calspa/input/dipep/GLHDv_OH_Term_fixed.clt
clt[55]=~/calspa/input/dipep/HIPDv.clt 
clt[56]=~/calspa/input/dipep/HIPDv_Term_fixed.clt
clt[57]=~/calspa/input/dipep/HIDDv.clt 
clt[58]=~/calspa/input/dipep/HIDDv_Term_fixed.clt
clt[59]=~/calspa/input/dipep/CYXDv.clt 
clt[60]=~/calspa/input/dipep/CYXDv_Term_fixed.clt
clt[61]=~/calspa/input/dipep/CYMDv.clt 
clt[61]=~/calspa/input/dipep/CYMDv_Term_fixed.clt
clt[63]=~/calspa/input/dipep/LYNDv.clt 
clt[64]=~/calspa/input/dipep/LYNDv_Term_fixed.clt
clt[65]=~/calspa/input/dipep/LYNDv_NH2_Term_fixed.clt

top=( dummy )
top[1]=~/calspa/input/dipep/GLYDv.top
top[2]=~/calspa/input/dipep/GLYDv.top
top[3]=~/calspa/input/dipep/ALADv.top
top[4]=~/calspa/input/dipep/ALADv.top
top[5]=~/calspa/input/dipep/ASPDv.top
top[6]=~/calspa/input/dipep/ASPDv.top
top[7]=~/calspa/input/dipep/GLUDv.top
top[8]=~/calspa/input/dipep/GLUDv.top
top[9]=~/calspa/input/dipep/LEUDv.top
top[10]=~/calspa/input/dipep/LEUDv.top
top[11]=~/calspa/input/dipep/ILEDv.top
top[12]=~/calspa/input/dipep/ILEDv.top
top[13]=~/calspa/input/dipep/ASNDv.top
top[14]=~/calspa/input/dipep/ASNDv.top
top[15]=~/calspa/input/dipep/ASNDv.top
top[16]=~/calspa/input/dipep/GLNDv.top
top[17]=~/calspa/input/dipep/GLNDv.top
top[18]=~/calspa/input/dipep/GLNDv.top
top[19]=~/calspa/input/dipep/VALDv.top
top[20]=~/calspa/input/dipep/VALDv.top
top[21]=~/calspa/input/dipep/HIEDv.top
top[22]=~/calspa/input/dipep/HIEDv.top
top[23]=~/calspa/input/dipep/SERDv.top
top[24]=~/calspa/input/dipep/SERDv.top
top[25]=~/calspa/input/dipep/SERDv.top
top[26]=~/calspa/input/dipep/THRDv.top
top[27]=~/calspa/input/dipep/THRDv.top
top[28]=~/calspa/input/dipep/THRDv.top
top[29]=~/calspa/input/dipep/METDv.top
top[30]=~/calspa/input/dipep/METDv.top
top[31]=~/calspa/input/dipep/METDv.top
top[32]=~/calspa/input/dipep/CYSDv.top
top[33]=~/calspa/input/dipep/CYSDv.top
top[34]=~/calspa/input/dipep/CYSDv.top
top[35]=~/calspa/input/dipep/PRODv.top
top[36]=~/calspa/input/dipep/PRODv.top
top[37]=~/calspa/input/dipep/ARGDv.top
top[38]=~/calspa/input/dipep/ARGDv.top
top[39]=~/calspa/input/dipep/ARGDv.top
top[40]=~/calspa/input/dipep/LYSDv.top
top[41]=~/calspa/input/dipep/LYSDv.top
top[42]=~/calspa/input/dipep/PHEDv.top
top[43]=~/calspa/input/dipep/PHEDv.top
top[44]=~/calspa/input/dipep/TY3Dv.top
top[45]=~/calspa/input/dipep/TY3Dv.top
top[46]=~/calspa/input/dipep/TY3Dv.top
top[47]=~/calspa/input/dipep/TRPDv.top
top[48]=~/calspa/input/dipep/TRPDv.top
top[49]=~/calspa/input/dipep/ASHDv.top
top[50]=~/calspa/input/dipep/ASHDv.top
top[51]=~/calspa/input/dipep/ASHDv.top
top[52]=~/calspa/input/dipep/GLHDv.top
top[53]=~/calspa/input/dipep/GLHDv.top
top[54]=~/calspa/input/dipep/GLHDv.top
top[55]=~/calspa/input/dipep/HIPDv.top
top[56]=~/calspa/input/dipep/HIPDv.top
top[57]=~/calspa/input/dipep/HIDDv.top
top[58]=~/calspa/input/dipep/HIDDv.top
top[59]=~/calspa/input/dipep/CYXDv.top
top[60]=~/calspa/input/dipep/CYXDv.top
top[61]=~/calspa/input/dipep/CYMDv.top
top[62]=~/calspa/input/dipep/CYMDv.top
top[63]=~/calspa/input/dipep/LYMDv.top
top[64]=~/calspa/input/dipep/LYMDv.top
top[65]=~/calspa/input/dipep/LYMDv.top

phi=( dummy -60 -135 )
psi=( dummy -45  150 )
omega=( dummy 180 0 )

T=600

numini=10
nCyc=200

Ncrds=$(expr ${#phi[*]} - 1)

TCMD=100
       
NUM=5

#NRES=$(expr ${#RES[*]} - 1)
#INIRES=3
#NRES=10
#INIRES=11
INIRES=1
NRES=65
