CC=mpicc

LIB=-lmpi -lm

#mpi1: mpi1.c
#	$(CC) -o mpi1 mpi1.c $(LIB)

##############################################
# mpi2: mpi2.c				     #
# 	$(CC) -o mpi2 mpi2.c $(LIB)	     #
##############################################

mpi2: mpi4.c
	$(CC) -o mpi4 mpi4.c $(LIB)
