C
C  *** PRECEP INPUT DATA CREATION PROGRAM ***
C      THIS PROGRAM CREATES PRECEP INPUT DATA
C
C
C      *** INPUT FILE ***
C          11    COORDINATE FILE ( ABE FORMAT )
C          13    DIHEDRAL ANGLE FILE ( ECEPP FORMAT )
C      *** OUTPUT FILE ***
C          12    PRECEP INPUT FILE
C
      SUBROUTINE PREIN
C
C     *** DECLARE ***
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
CMSP  INCLUDE (COMMAND)
C COMMAND.CMN
C
C PURPOSE : COMMON BLOCKS FOR PARSER
C
      COMMON/COMMAN /COMLYN(2000)
      COMMON/COMMSI  /COMLEN,MXCMSZ
      CHARACTER*1 COMLYN
      INTEGER COMLEN
      EQUIVALENCE (COMLYN(1),COMLY2 )
      CHARACTER*2000 COMLY2
C
C     COMLYN  - STORES CHARACTERS IN INPUT (COMMAND) LINE, UP TO 2000
C               CHARACTERS
C     COMLEN  - ACTUAL NUMBER OF NON-BLANK CHARACTERS
C     MXCMSZ  - MAX NUMBER OF CHARACTERS = 2000
C     COMLYN2 - A CHARACTER*2000 REPRESENTATION OF THE COMMAND LINE
C
CMSP  INCLUDE (MAXSIZE)
C MAXSIZE
C     MAXSIZE DEFINES MAXIMUM ARRAY SIZE
C
      PARAMETER(MAXATM=2050,MAXVAR=800,MAXRES=150,MAXSS=10,
     >          MXRS1=MAXRES+1,MXRS10=10*MAXRES,MAXLEN=6000,
     >          MAXDBL=1000,MAXDP=700,MAXDPL=MAXATM+MAXDBL/2,
     >          MAXDP2=MAXDP*2,MXPAIR=MAXVAR*(MAXVAR+1)/2,
     >          MXPAR1=(MAXVAR+1)*(MAXVAR+2)/2,MAXPER=16000,
     >          MAXCNS=900,MAXJ=2*MAXVAR,MAXSS2=MAXSS*2,
     >          MAXINT=40000,MAXI1=MAXINT/2,MAXI2=MAXINT-MAXI1,
     >          MXATM1=MAXATM+1,MVAR1=MAXVAR+1,
     >          MWORK=100000,MIWORK=100000,MCHWOR=100000)
C
C  MAXAT:  MAXIMUM NUMBER OF ATOMS IN A PROTEIN
C  MAXVAR: MAXMUM NUMBER OF DIHEDRAL ANGLE VARIABLES
C  MAXRS:  MAXMUM NUMBER OF RESIDUES
C  MAXSS:  MAXMUM NUMBER OF S-S CROSSLINK
C  MXRS1:  MAXRS+1
C  MXRS10: MAXRS*10
C  MAXLEN: ARRAY SIZE OF INTER IN PREP IN PRECEP ?
C  MAXDBL: MAXMUM NUMBER OF DIPOLES (?)
C  MWORK:  MAXIMUM SIZE OF REAL WORK ARRAY
C  MIWORK: MAXIMUM SIZE OF INTEGER WORK ARRAY
C  MCWORK: MAXIMUM SIZE OF CHARACTER WORK ARRAY
CMSP  INCLUDE (UNITNUMS)
C  UNITNUMS.CMN
C
C  THIS FILE CONTAINS THE  COMMON BLOCK NECESSARY
C  TO ASSIGN ALL I/0 UNIT NUMBERS. A SUMMARY OF ALL I/O FILES USED BY
C  IMPACT APPEARS BELOW, ORGANIZED BY TASK.
C
C
      COMMON/UNITNU  /IN1,IN2,IN3,IN4,IFN4,
     *               IOUT1,IOUT2,IOUT3,
     * IN01,IOUT02,IOUT06,
C
C PREIN
C
     * IN11,IN13,IOUT12,IOUT14,IOUT16,IN15,IN17,IOUT18,IN19,IOUT20,
C
C PRECEP
C
     * IN21,IN23,IN25,IN27,IN29,
     * IOUT22,IOUT24,IOUT26,IOUT28,IOUT30,
C
C MINIMIZATION
C
     * IN31,IN33,IN35,IN37,IN39,
     * IOUT32,IOUT34,IOUT36,IOUT38,IOUT39,IOUT40,
C
C NORMAL MODE
C
     * IN41,IN43,IN45,IN47,IN49,
     * IOUT42,IOUT44,IOUT46,IOUT48,IOUT50,IOUT52,IOUT54,IOUT56,IOUT58,
     * IOUT60,IOUT62,IOUT64,IOUT66,
C
C MONTE CARLO
C
     * IN71,IN73,IN75,IN77,IN79,
     * IOUT72,IOUT74,IOUT76,IOUT78
C
C PRIMARY INPUT FILE ----- IN01
C PRIMARY OUTPUT FILE ---- IOUT02
C PRIMARY LOG FILE ------- IOUT06
C
C ODD NUMBERS ARE RESERVED FOR INPUT,
C EVEN NUMBERS ARE RESERVED FOR OUTPUT
C FOR EXPLICIT DEFINITIONS OF INPUT AND OUTPUT FILES, PLEASE SEE MAIN
CMSP  INCLUDE (ALPHA)
C ALPHA
C
      CHARACTER*4  ATNAME,RENAME
      CHARACTER*80 TITLE
      COMMON/ALPHA1/ATNAME(MAXATM),RENAME(MAXATM)
      COMMON/ALPHA2/NMBRES(MAXATM)
      COMMON/TITLE/TITLE
C
C  ATNAME:   ATOM NAMES (ECEPP ORDER)
C  RENAME :   RESIDUE NAMES (ECEPP ORDER)
C  NMBRES :   RESIDUE NUMBER (NORMAL NUMBERING)
C  TITLE  :   TITLE OF PRECEP
C
CMSP  INCLUDE (SIZE)
C SIZE
C  THIS COMMON BLOCK STORES THE NUMBERS RELATED TO PROTEIN SIZE
C
      COMMON/SIZE/NUMATM,NUMVAR,NN2,NUMINT,NSS,NUMRES
      COMMON/SIZE1/NATM1,NVAR1,NPAIR1
C
C  NUMATM:   NUMBER OF ATOMS IN A PROTEIN
C  NUMVAR:   NUMBER OF (DIHEDRAL) ANGLE VARIABLES
C  NN2:      NUMVAR*(NUMVAR+1)/2
C  NUMINT:     ?
C  NSS:      NUMBER OF S-S CROSSLINK (?)
C  NUMRES:   NUMBER OF RESIDUES
C  NATM1=NUMATM+1
C  NVAR1=NUMVAR+1
C  NPAIR1=(NUMVAR+1)*(NUMVAR+2)/2
CMSP  INCLUDE (CNTL)
C CNTL
C
       COMMON /PRINT/IPRNT
C
C   IPRNT :  PRINT OPTION, 0 PART OUTPUT, 1 ALL OUTPUT
C
CMSP  INCLUDE (PRIMRY)
C PRIMRY
C
       INTEGER LIST
       COMMON /PRIMRY/LIST(MAXRES)
C
C   LIST : AMINO ACID RESIDUE NUMBER
C
CMSP  INCLUDE (SSPAIR)
C SSPAIR
C
      COMMON/SSPAIR/KSSPER(6,2,MAXSS),JSS(3,MAXSS),KSS(MAXSS2),
     >              LSS(MAXSS2),NPAIR(MAXSS,2)
C
C  KSSPER:    THE ATOM NUMBERS WHICH BELONG TO THE DISULPHITE BONDS
C
CMSP  INCLUDE (VARANG)
C VARANG
C
      COMMON/VARANG/ANGRAD(10,MAXRES),VAR(MAXVAR),INDXV(MAXVAR),
     >              ANGLES(10,MAXRES)
C
C  ANGRAD :  DIHEDRAL ANGLES IN ECCEP ORDER (RADIAN)
C  VAR:    DIHEDRAL ANGLES IN WAKO ORDER (RADIAN)
C  INDXV : INDVX=NNN*100+MMM (MMM:1-10)
C            NNN: RESIDUE NUMBER
C            MMM: DIHEDRAL ANGLE NUMBER IN THE RESIDUE(NNN) IN ECEPP
C                 ORDER
C  ANGLES: DIHEDRAL ANGLES IN ECEPP ORDER (DEGREE)
C          USED AS THE WORK]]
C
      CHARACTER*60 NAME
      CHARACTER*11 FORMA
      CHARACTER*4  SUBTAS,NXTWD
      CHARACTER*4  DAOP
      CHARACTER*1  ENDOP
C
      INTEGER NURESV,NENDN,CENDN
      INTEGER RESNU(MAXRES),NUDA(MAXRES),DANU(MAXRES,10)
C
C     *** VARIABLE LIST ***
C     MAXRES = MAX NUMBER OF RESIDUES
C     MAXSS = MAX NUMBER OF S-S
C     NURES = NUMBER OF RESIDUES ( NUMER OF AMINO ACIDS + 2 )
C     NUSS = NUMBER OF S-S
C     PROP = PRINT OPTION ; 0 : PART OUTPUT  1 : ALL OUTPUT
C]]]]]]]] PROP CHANGED TO IPRNT BY A. KITAO FEB 16, 1990]]]]]]]]]]]]]]]]
C     DAOP = DIHEDRAL ANGLES OPTION ;  'ALL ','BACK','SIDE','SPEC'
C            'ALL ' ; ALL DIHEDRAL ANGLES ARE TO BE VARIED
C            'BACK' ; ALL BACKBONE DIHEDRAL ANGLES AND ALL END GROUP
C                     DIHEDRAL ANGLES ARE TO BE VARIED
C            'SIDE' ; ALL SIDE-CHAIN DIHEDRAL ANGLES ARE TO BE VARIED
C            'SPEC' ; ONLY THOSE DIHEDRAL ANGLES SPECIFIED EXPLICITLY
C                     BY SUBSEQUENT DATA ARE TO BE VARIED
C     ENDOP = END GROUP OPTION ;  'Y ' OR 'N'
C     NURESV = NUMBER OF RESIDUES WHICH HAVE VARIABL DIHEDRAL ANGLES
C     NENDN = N-END GROUP NUMBER WHICN USER SPECIFY
C     CENDN = C-END GROUP NUMBER WHICN USER SPECIFY
C     LIST(I) = RESIDUE SEQUENCE BY NUMBER
C     RESNU(I) = RESIDUE NUMBER WHICH HAS VARIABLE DIHEDRAL ANGLES
C     NUDA(I) = NUMBER OF VARIABLE DIHEDRAL ANGLES OF RESIDUE I
C     DANU(I,J) = DIHEDRAL ANGLE NUMBER OF RESIDUE I
C     CYSPAIR(I,J) = CYS(S-S) RESIDUE NUMBER
C
C    IPRNT IS FIXED TO 0
C    DAOP IS FIXED TO 'ALL '
      IPRNT = 0
      DAOP = 'ALL '
C
C     *** GET SUBTASK
C
  999 CONTINUE
      CALL NXTCMN(SUBTAS)
      WRITE(IOUT02,10) SUBTAS
   10 FORMAT(/5X,' NEXT SUBTASK * ', A4,/)
C
C      *** SUBTASK QUIT
C
      IF(SUBTAS .EQ. 'QUIT') GOTO 629
C
C      *** SUBTASK BUILD
C
      IF(SUBTAS .EQ. 'BUIL') THEN
          CALL NXTWRD(COMLY2, COMLEN, NXTWD, 4)
          IF(NXTWD .EQ. 'PRIM') THEN
C         *** READ PRIMARY STRUCTURE
              CALL PRIM(NUMRES)
          ELSEIF(NXTWD .EQ. 'CROS') THEN
C         *** READ CROSSLINK
              CALL CROSS(NSS,NPAIR)
          ELSEIF(NXTWD .EQ. 'READ') THEN
C         *** READ RESIDUE SEQUENCE DATA
              CALL GTFLNM(NAME)
              FORMA = 'FORMATTED'
              CALL OPENRD(IN11,FORMA,NAME,IOUT06)
              WRITE(IOUT02,20) NXTWD,NAME
   20         FORMAT(5X,A4,' : READ FROM ',A60)
              CALL RDABE(NUMRES,NSS,NPAIR)
              CLOSE(IN11)
          ELSEIF(NXTWD .EQ. 'END ') THEN
C         *** SPECIFY END-GROUP
C           IF YOU DON'T SPECIFY END GROUP , N-END GROUP IS 'H2N'
C           AND C-END GROUP IS 'COOH' .
              ENDOP =  'Y'
C             *** GET N-END NUMBER
              CALL GETPAI(COMLY2, COMLEN, 'NEND',4, ' ', 0, NENDN)
C             *** GET C-END NUMBER
              CALL GETPAI(COMLY2, COMLEN, 'CEND',4, ' ', 0, CENDN)
              WRITE(IOUT02,40)
              WRITE(IOUT02,50)
              WRITE(IOUT02,60) NENDN,CENDN
              WRITE(IOUT06,40)
              WRITE(IOUT06,50)
              WRITE(IOUT06,60) NENDN,CENDN
   40         FORMAT(6X,'*** END GROUP ***    ')
   50         FORMAT(5X,'   DEFAULT     N-END   1  C-END  11')
   60         FORMAT(5X,'   CHANGED TO  N-END  ',I2,'  C-END  ',I2)
              LIST(1)=NENDN
              LIST(NUMRES)=CENDN
          ENDIF
       ENDIF
C
C      *** SUBTASK READ
C
      IF(SUBTAS .EQ. 'READ') THEN
          CALL NXTWRD(COMLY2, COMLEN, NXTWD, 4)
          IF(NXTWD .EQ. 'ANGL') THEN
C     *** READ DIHEDRAL ANGLE DATA
              CALL GTFLNM(NAME)
              FORMA = 'FORMATTED'
              CALL OPENRD(IN13,FORMA,NAME,IOUT06)
              WRITE(IOUT02,20) NXTWD,NAME
              CALL RDANGL(IN13)
              CLOSE(IN13)
           ENDIF
      ENDIF
C
C      *** SUBTASK WRITE
C
      IF(SUBTAS .EQ. 'WRIT') THEN
          CALL NXTWRD(COMLY2, COMLEN, NXTWD, 4)
          IF(NXTWD .EQ. 'ANGL') THEN
C         *** WRITE ANGLE DATA (ECEPP FORMAT)
              CALL GTFLNM(NAME)
              FORMA = 'FORMATTED'
              CALL OPENWT(IOUT14,FORMA,NAME,IOUT06)
              WRITE(IOUT02,30) NXTWD,NAME
              CALL WTANGL(IOUT14)
              CLOSE(IOUT14)
          ELSEIF(NXTWD .EQ. 'ABE ') THEN
C         *** WRITE SEQUENCE DATA (ABE FORMAT)
              WRITE(IOUT02,*) '     NOT SUPPORTEDIN THIS VERSION]]'
          ELSEIF(NXTWD .EQ. 'PREI') THEN
C         *** WRITE INPUT DATA FORT PRECEP
              CALL GTFLNM(NAME)
              FORMA = 'FORMATTED'
              CALL OPENWT(IOUT12,FORMA,NAME,IOUT06)
              WRITE(IOUT02,30) NXTWD,NAME
   30         FORMAT(5X,A4,' : WRITE TO  ',A60)
              CALL WTPRIN(NUMRES,IPRNT,NSS,NPAIR,DAOP,
     1                  NURESV,RESNU,NUDA,DANU)
              CLOSE(IOUT12)
          ENDIF
       ENDIF
C
C      *** RETURN TO THE TOP OF THE LOOP
C
       GOTO 999
C
  629 RETURN
      END
C
C     THIS SUBROUTINE READS TITLE NURES,NUSS,CYSPAIR(I,J),AA(I)
C     FROM C.DATA FILE AND CONVERT AA(I)(4 CHARACTER RESIDUE SEQUENCE)
C     TO LIST(I)(NUMBER RESIDUE SEQUENCE)
C
      SUBROUTINE RDABE(NURES,NUSS,SSPAIR)
C
C     *** DECLARE ***
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
CMSP  INCLUDE (MAXSIZE)
C MAXSIZE
C     MAXSIZE DEFINES MAXIMUM ARRAY SIZE
C
      PARAMETER(MAXATM=2050,MAXVAR=800,MAXRES=150,MAXSS=10,
     >          MXRS1=MAXRES+1,MXRS10=10*MAXRES,MAXLEN=6000,
     >          MAXDBL=1000,MAXDP=700,MAXDPL=MAXATM+MAXDBL/2,
     >          MAXDP2=MAXDP*2,MXPAIR=MAXVAR*(MAXVAR+1)/2,
     >          MXPAR1=(MAXVAR+1)*(MAXVAR+2)/2,MAXPER=16000,
     >          MAXCNS=900,MAXJ=2*MAXVAR,MAXSS2=MAXSS*2,
     >          MAXINT=40000,MAXI1=MAXINT/2,MAXI2=MAXINT-MAXI1,
     >          MXATM1=MAXATM+1,MVAR1=MAXVAR+1,
     >          MWORK=100000,MIWORK=100000,MCHWOR=100000)
C
C  MAXAT:  MAXIMUM NUMBER OF ATOMS IN A PROTEIN
C  MAXVAR: MAXMUM NUMBER OF DIHEDRAL ANGLE VARIABLES
C  MAXRS:  MAXMUM NUMBER OF RESIDUES
C  MAXSS:  MAXMUM NUMBER OF S-S CROSSLINK
C  MXRS1:  MAXRS+1
C  MXRS10: MAXRS*10
C  MAXLEN: ARRAY SIZE OF INTER IN PREP IN PRECEP ?
C  MAXDBL: MAXMUM NUMBER OF DIPOLES (?)
C  MWORK:  MAXIMUM SIZE OF REAL WORK ARRAY
C  MIWORK: MAXIMUM SIZE OF INTEGER WORK ARRAY
C  MCWORK: MAXIMUM SIZE OF CHARACTER WORK ARRAY
CMSP  INCLUDE (ALPHA)
C ALPHA
C
      CHARACTER*4  ATNAME,RENAME
      CHARACTER*80 TITLE
      COMMON/ALPHA1/ATNAME(MAXATM),RENAME(MAXATM)
      COMMON/ALPHA2/NMBRES(MAXATM)
      COMMON/TITLE/TITLE
C
C  ATNAME:   ATOM NAMES (ECEPP ORDER)
C  RENAME :   RESIDUE NAMES (ECEPP ORDER)
C  NMBRES :   RESIDUE NUMBER (NORMAL NUMBERING)
C  TITLE  :   TITLE OF PRECEP
C
CMSP  INCLUDE (COMMAND)
C COMMAND.CMN
C
C PURPOSE : COMMON BLOCKS FOR PARSER
C
      COMMON/COMMAN /COMLYN(2000)
      COMMON/COMMSI  /COMLEN,MXCMSZ
      CHARACTER*1 COMLYN
      INTEGER COMLEN
      EQUIVALENCE (COMLYN(1),COMLY2 )
      CHARACTER*2000 COMLY2
C
C     COMLYN  - STORES CHARACTERS IN INPUT (COMMAND) LINE, UP TO 2000
C               CHARACTERS
C     COMLEN  - ACTUAL NUMBER OF NON-BLANK CHARACTERS
C     MXCMSZ  - MAX NUMBER OF CHARACTERS = 2000
C     COMLYN2 - A CHARACTER*2000 REPRESENTATION OF THE COMMAND LINE
C
CMSP  INCLUDE (UNITNUMS)
C  UNITNUMS.CMN
C
C  THIS FILE CONTAINS THE  COMMON BLOCK NECESSARY
C  TO ASSIGN ALL I/0 UNIT NUMBERS. A SUMMARY OF ALL I/O FILES USED BY
C  IMPACT APPEARS BELOW, ORGANIZED BY TASK.
C
C
      COMMON/UNITNU  /IN1,IN2,IN3,IN4,IFN4,
     *               IOUT1,IOUT2,IOUT3,
     * IN01,IOUT02,IOUT06,
C
C PREIN
C
     * IN11,IN13,IOUT12,IOUT14,IOUT16,IN15,IN17,IOUT18,IN19,IOUT20,
C
C PRECEP
C
     * IN21,IN23,IN25,IN27,IN29,
     * IOUT22,IOUT24,IOUT26,IOUT28,IOUT30,
C
C MINIMIZATION
C
     * IN31,IN33,IN35,IN37,IN39,
     * IOUT32,IOUT34,IOUT36,IOUT38,IOUT39,IOUT40,
C
C NORMAL MODE
C
     * IN41,IN43,IN45,IN47,IN49,
     * IOUT42,IOUT44,IOUT46,IOUT48,IOUT50,IOUT52,IOUT54,IOUT56,IOUT58,
     * IOUT60,IOUT62,IOUT64,IOUT66,
C
C MONTE CARLO
C
     * IN71,IN73,IN75,IN77,IN79,
     * IOUT72,IOUT74,IOUT76,IOUT78
C
C PRIMARY INPUT FILE ----- IN01
C PRIMARY OUTPUT FILE ---- IOUT02
C PRIMARY LOG FILE ------- IOUT06
C
C ODD NUMBERS ARE RESERVED FOR INPUT,
C EVEN NUMBERS ARE RESERVED FOR OUTPUT
C FOR EXPLICIT DEFINITIONS OF INPUT AND OUTPUT FILES, PLEASE SEE MAIN
CMSP  INCLUDE (PRIMRY)
C PRIMRY
C
       INTEGER LIST
       COMMON /PRIMRY/LIST(MAXRES)
C
C   LIST : AMINO ACID RESIDUE NUMBER
C
C
      INTEGER NURES,NUSS,SSPAIR(MAXSS,2)
C
      CHARACTER*4 AA(MAXRES)
      CHARACTER*144 BAA
C
C     *** VARIABLE LIST ***
C     BAA = 36 AMINO ACIDS REPRESENTED BY 4 CHARACTERS
C
      BAA='ALA ASP CYS GLU PHE GLY HIS ILE LYS LEU MET ASN ' //
     1    'PRO GLN ARG SER THR VAL TRP TYR CYE HPR NLE ORN ' //
     2    'ORN+HIS2HIS+LYS+ARG+ASB ASP-GLU-PROUPROFHPRUHPRF'
C
C     *** READ DATA FROM C.DATA FILE ***
C
      READ(IN11,1000)TITLE
 1000 FORMAT(A80)
      READ(IN11,1001)NURES,NUSS
 1001 FORMAT(I5,10X,I5)
      IF(NURES.GT.MAXRES)GO TO 1
      IF(NUSS.GT.MAXSS)GO TO 1
      READ(IN11,1002)(AA(I),I=1,NURES)
 1002 FORMAT(5X,10A4)
      IF(NUSS.NE.0)THEN
        READ(IN11,1003)((SSPAIR(I,J),J=1,2),I=1,NUSS)
 1003   FORMAT(20I4)
      ENDIF
C
C        ** CONVERT AA(I) TO LIST(I) **
C
      DO 10 I=2,NURES-1
        J=INDEX(BAA,AA(I))
        LIST(I)=(J+3)/4
   10 CONTINUE
C
C        ** N-END GROUP IS 'H2N' (1)  **
C        ** C-END GROUP IS 'COOH'(11) **
C
      LIST(1)=1
      LIST(NURES)=11
      RETURN
C
    1 CONTINUE
      WRITE(IOUT02,600)
  600 FORMAT(' ','   NUMBER OVER')
      WRITE(IOUT02,601)NURES,MAXRES,NUSS,MAXSS
  601 FORMAT(' ',' NUMBER OF RESIDUES',I5,'(MAX=',I5,') :'/
     1           ' NUMBER OF S-S     ',I5,'(MAX=',I5,')')
C
      STOP
      END
C
C     THIS SUBROUTINE READS NUSS,SSPAIR(I,J) FROM INPUT FILE
C
      SUBROUTINE CROSS(NUSS,SSPAIR)
C
C     *** DECLARE ***
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
CMSP  INCLUDE (COMMAND)
C COMMAND.CMN
C
C PURPOSE : COMMON BLOCKS FOR PARSER
C
      COMMON/COMMAN /COMLYN(2000)
      COMMON/COMMSI  /COMLEN,MXCMSZ
      CHARACTER*1 COMLYN
      INTEGER COMLEN
      EQUIVALENCE (COMLYN(1),COMLY2 )
      CHARACTER*2000 COMLY2
C
C     COMLYN  - STORES CHARACTERS IN INPUT (COMMAND) LINE, UP TO 2000
C               CHARACTERS
C     COMLEN  - ACTUAL NUMBER OF NON-BLANK CHARACTERS
C     MXCMSZ  - MAX NUMBER OF CHARACTERS = 2000
C     COMLYN2 - A CHARACTER*2000 REPRESENTATION OF THE COMMAND LINE
C
CMSP  INCLUDE (MAXSIZE)
C MAXSIZE
C     MAXSIZE DEFINES MAXIMUM ARRAY SIZE
C
      PARAMETER(MAXATM=2050,MAXVAR=800,MAXRES=150,MAXSS=10,
     >          MXRS1=MAXRES+1,MXRS10=10*MAXRES,MAXLEN=6000,
     >          MAXDBL=1000,MAXDP=700,MAXDPL=MAXATM+MAXDBL/2,
     >          MAXDP2=MAXDP*2,MXPAIR=MAXVAR*(MAXVAR+1)/2,
     >          MXPAR1=(MAXVAR+1)*(MAXVAR+2)/2,MAXPER=16000,
     >          MAXCNS=900,MAXJ=2*MAXVAR,MAXSS2=MAXSS*2,
     >          MAXINT=40000,MAXI1=MAXINT/2,MAXI2=MAXINT-MAXI1,
     >          MXATM1=MAXATM+1,MVAR1=MAXVAR+1,
     >          MWORK=100000,MIWORK=100000,MCHWOR=100000)
C
C  MAXAT:  MAXIMUM NUMBER OF ATOMS IN A PROTEIN
C  MAXVAR: MAXMUM NUMBER OF DIHEDRAL ANGLE VARIABLES
C  MAXRS:  MAXMUM NUMBER OF RESIDUES
C  MAXSS:  MAXMUM NUMBER OF S-S CROSSLINK
C  MXRS1:  MAXRS+1
C  MXRS10: MAXRS*10
C  MAXLEN: ARRAY SIZE OF INTER IN PREP IN PRECEP ?
C  MAXDBL: MAXMUM NUMBER OF DIPOLES (?)
C  MWORK:  MAXIMUM SIZE OF REAL WORK ARRAY
C  MIWORK: MAXIMUM SIZE OF INTEGER WORK ARRAY
C  MCWORK: MAXIMUM SIZE OF CHARACTER WORK ARRAY
CMSP  INCLUDE (UNITNUMS)
C  UNITNUMS.CMN
C
C  THIS FILE CONTAINS THE  COMMON BLOCK NECESSARY
C  TO ASSIGN ALL I/0 UNIT NUMBERS. A SUMMARY OF ALL I/O FILES USED BY
C  IMPACT APPEARS BELOW, ORGANIZED BY TASK.
C
C
      COMMON/UNITNU  /IN1,IN2,IN3,IN4,IFN4,
     *               IOUT1,IOUT2,IOUT3,
     * IN01,IOUT02,IOUT06,
C
C PREIN
C
     * IN11,IN13,IOUT12,IOUT14,IOUT16,IN15,IN17,IOUT18,IN19,IOUT20,
C
C PRECEP
C
     * IN21,IN23,IN25,IN27,IN29,
     * IOUT22,IOUT24,IOUT26,IOUT28,IOUT30,
C
C MINIMIZATION
C
     * IN31,IN33,IN35,IN37,IN39,
     * IOUT32,IOUT34,IOUT36,IOUT38,IOUT39,IOUT40,
C
C NORMAL MODE
C
     * IN41,IN43,IN45,IN47,IN49,
     * IOUT42,IOUT44,IOUT46,IOUT48,IOUT50,IOUT52,IOUT54,IOUT56,IOUT58,
     * IOUT60,IOUT62,IOUT64,IOUT66,
C
C MONTE CARLO
C
     * IN71,IN73,IN75,IN77,IN79,
     * IOUT72,IOUT74,IOUT76,IOUT78
C
C PRIMARY INPUT FILE ----- IN01
C PRIMARY OUTPUT FILE ---- IOUT02
C PRIMARY LOG FILE ------- IOUT06
C
C ODD NUMBERS ARE RESERVED FOR INPUT,
C EVEN NUMBERS ARE RESERVED FOR OUTPUT
C FOR EXPLICIT DEFINITIONS OF INPUT AND OUTPUT FILES, PLEASE SEE MAIN
CMSP  INCLUDE (PRIMRY)
C PRIMRY
C
       INTEGER LIST
       COMMON /PRIMRY/LIST(MAXRES)
C
C   LIST : AMINO ACID RESIDUE NUMBER
C
C
      INTEGER NUSS,SSPAIR(MAXSS,2)
C
C     *** READ CROSS LINK DATA FROM INPUT FILE
C
      DO 10 I=1,99999
         CALL GETPAI(COMLY2, COMLEN, 'CYS1',4, ' ', 0, SSPAIR(I,1))
         CALL GETPAI(COMLY2, COMLEN, 'CYS2',4, ' ', 0, SSPAIR(I,2))
         IF(SSPAIR(I,1) .EQ. 0 .OR. SSPAIR(I,2) .EQ. 0) GOTO 20
         SSPAIR(I,1) = SSPAIR(I,1) + 1
         SSPAIR(I,2) = SSPAIR(I,2) + 1
   10 CONTINUE
C
   20 NUSS = I - 1
C
      WRITE(IOUT02,*)'     *** CROSS LINK ***'
      WRITE(IOUT06,*)'     *** CROSS LINK ***'
      DO 30 I=1,NUSS
      WRITE(IOUT02,*)'       CYS1 : ',SSPAIR(I,1),' CYS2 : ',SSPAIR(I,2)
      WRITE(IOUT06,*)'       CYS1 : ',SSPAIR(I,1),' CYS2 : ',SSPAIR(I,2)
   30 CONTINUE
C
      RETURN
      END
C
C     THIS SUBROUTINE READ AMID ACID SEQUENCE AND GENERATE LIST(I)
C     WHICH ARE AMINO ACID NUMBER
C
      SUBROUTINE PRIM(NURES)
C
C     *** DECLARE ***
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
CMSP  INCLUDE (MAXSIZE)
C MAXSIZE
C     MAXSIZE DEFINES MAXIMUM ARRAY SIZE
C
      PARAMETER(MAXATM=2050,MAXVAR=800,MAXRES=150,MAXSS=10,
     >          MXRS1=MAXRES+1,MXRS10=10*MAXRES,MAXLEN=6000,
     >          MAXDBL=1000,MAXDP=700,MAXDPL=MAXATM+MAXDBL/2,
     >          MAXDP2=MAXDP*2,MXPAIR=MAXVAR*(MAXVAR+1)/2,
     >          MXPAR1=(MAXVAR+1)*(MAXVAR+2)/2,MAXPER=16000,
     >          MAXCNS=900,MAXJ=2*MAXVAR,MAXSS2=MAXSS*2,
     >          MAXINT=40000,MAXI1=MAXINT/2,MAXI2=MAXINT-MAXI1,
     >          MXATM1=MAXATM+1,MVAR1=MAXVAR+1,
     >          MWORK=100000,MIWORK=100000,MCHWOR=100000)
C
C  MAXAT:  MAXIMUM NUMBER OF ATOMS IN A PROTEIN
C  MAXVAR: MAXMUM NUMBER OF DIHEDRAL ANGLE VARIABLES
C  MAXRS:  MAXMUM NUMBER OF RESIDUES
C  MAXSS:  MAXMUM NUMBER OF S-S CROSSLINK
C  MXRS1:  MAXRS+1
C  MXRS10: MAXRS*10
C  MAXLEN: ARRAY SIZE OF INTER IN PREP IN PRECEP ?
C  MAXDBL: MAXMUM NUMBER OF DIPOLES (?)
C  MWORK:  MAXIMUM SIZE OF REAL WORK ARRAY
C  MIWORK: MAXIMUM SIZE OF INTEGER WORK ARRAY
C  MCWORK: MAXIMUM SIZE OF CHARACTER WORK ARRAY
CMSP  INCLUDE (COMMAND)
C COMMAND.CMN
C
C PURPOSE : COMMON BLOCKS FOR PARSER
C
      COMMON/COMMAN /COMLYN(2000)
      COMMON/COMMSI  /COMLEN,MXCMSZ
      CHARACTER*1 COMLYN
      INTEGER COMLEN
      EQUIVALENCE (COMLYN(1),COMLY2 )
      CHARACTER*2000 COMLY2
C
C     COMLYN  - STORES CHARACTERS IN INPUT (COMMAND) LINE, UP TO 2000
C               CHARACTERS
C     COMLEN  - ACTUAL NUMBER OF NON-BLANK CHARACTERS
C     MXCMSZ  - MAX NUMBER OF CHARACTERS = 2000
C     COMLYN2 - A CHARACTER*2000 REPRESENTATION OF THE COMMAND LINE
C
CMSP  INCLUDE (UNITNUMS)
C  UNITNUMS.CMN
C
C  THIS FILE CONTAINS THE  COMMON BLOCK NECESSARY
C  TO ASSIGN ALL I/0 UNIT NUMBERS. A SUMMARY OF ALL I/O FILES USED BY
C  IMPACT APPEARS BELOW, ORGANIZED BY TASK.
C
C
      COMMON/UNITNU  /IN1,IN2,IN3,IN4,IFN4,
     *               IOUT1,IOUT2,IOUT3,
     * IN01,IOUT02,IOUT06,
C
C PREIN
C
     * IN11,IN13,IOUT12,IOUT14,IOUT16,IN15,IN17,IOUT18,IN19,IOUT20,
C
C PRECEP
C
     * IN21,IN23,IN25,IN27,IN29,
     * IOUT22,IOUT24,IOUT26,IOUT28,IOUT30,
C
C MINIMIZATION
C
     * IN31,IN33,IN35,IN37,IN39,
     * IOUT32,IOUT34,IOUT36,IOUT38,IOUT39,IOUT40,
C
C NORMAL MODE
C
     * IN41,IN43,IN45,IN47,IN49,
     * IOUT42,IOUT44,IOUT46,IOUT48,IOUT50,IOUT52,IOUT54,IOUT56,IOUT58,
     * IOUT60,IOUT62,IOUT64,IOUT66,
C
C MONTE CARLO
C
     * IN71,IN73,IN75,IN77,IN79,
     * IOUT72,IOUT74,IOUT76,IOUT78
C
C PRIMARY INPUT FILE ----- IN01
C PRIMARY OUTPUT FILE ---- IOUT02
C PRIMARY LOG FILE ------- IOUT06
C
C ODD NUMBERS ARE RESERVED FOR INPUT,
C EVEN NUMBERS ARE RESERVED FOR OUTPUT
C FOR EXPLICIT DEFINITIONS OF INPUT AND OUTPUT FILES, PLEASE SEE MAIN
CMSP  INCLUDE (PRIMRY)
C PRIMRY
C
       INTEGER LIST
       COMMON /PRIMRY/LIST(MAXRES)
C
C   LIST : AMINO ACID RESIDUE NUMBER
C
C
      INTEGER NURES
      CHARACTER*4 AA(MAXRES)
      CHARACTER*4 RESNAM
      CHARACTER*144 BAA
C
C     *** VARIABLE LIST ***
C     BAA = 36 AMINO ACIDS REPRESENTED BY 4 CHARACTERS
C
      BAA='ALA ASP CYS GLU PHE GLY HIS ILE LYS LEU MET ASN ' //
     1    'PRO GLN ARG SER THR VAL TRP TYR CYE HPR NLE ORN ' //
     2    'ORN+HIS2HIS+LYS+ARG+ASB ASP-GLU-PROUPROFHPRUHPRF'
C
C     *** READ AMINO ACID SEQUENCE FORM INPUT DATA
C
      DO 10 I=2,99999
         CALL NXTWRD(COMLY2, COMLEN, RESNAM, 4)
         IF(RESNAM .EQ. 'END ') THEN
            GOTO 20
         ELSE
            AA(I) = RESNAM
         ENDIF
   10 CONTINUE
C
   20 NURES = I
C
C     *** CONVERT AA(I) TO LIST(I) **
C
      DO 30 I=2,NURES-1
         J = INDEX(BAA,AA(I))
         LIST(I) = (J+3)/4
   30 CONTINUE
C
      WRITE(IOUT02,* ) '     *** PRIMARY STRUCTURE *** '
      WRITE(IOUT02,11) (AA(I),  I=2,NURES-1)
      WRITE(IOUT02,21) (LIST(I), I=2,NURES-1)
      WRITE(IOUT06,* ) '     *** PRIMARY STRUCTURE *** '
      WRITE(IOUT06,11) (AA(I),  I=2,NURES-1)
      WRITE(IOUT06,21) (LIST(I), I=2,NURES-1)
   11 FORMAT(8X,10(A4,2X))
   21 FORMAT(7X,10(I4,2X))
C
      RETURN
      END
C
C     THIS SUBROUTINE WRITE DATA TO PRECEP INPUT FILE
C
      SUBROUTINE WTPRIN(NURES,IPRNT,NUSS,SSPAIR,DAOP,NURESV,
     1               RESNU,NUDA,DANU)
C
C     *** DECLARE ***
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
CMSP  INCLUDE (MAXSIZE)
C MAXSIZE
C     MAXSIZE DEFINES MAXIMUM ARRAY SIZE
C
      PARAMETER(MAXATM=2050,MAXVAR=800,MAXRES=150,MAXSS=10,
     >          MXRS1=MAXRES+1,MXRS10=10*MAXRES,MAXLEN=6000,
     >          MAXDBL=1000,MAXDP=700,MAXDPL=MAXATM+MAXDBL/2,
     >          MAXDP2=MAXDP*2,MXPAIR=MAXVAR*(MAXVAR+1)/2,
     >          MXPAR1=(MAXVAR+1)*(MAXVAR+2)/2,MAXPER=16000,
     >          MAXCNS=900,MAXJ=2*MAXVAR,MAXSS2=MAXSS*2,
     >          MAXINT=40000,MAXI1=MAXINT/2,MAXI2=MAXINT-MAXI1,
     >          MXATM1=MAXATM+1,MVAR1=MAXVAR+1,
     >          MWORK=100000,MIWORK=100000,MCHWOR=100000)
C
C  MAXAT:  MAXIMUM NUMBER OF ATOMS IN A PROTEIN
C  MAXVAR: MAXMUM NUMBER OF DIHEDRAL ANGLE VARIABLES
C  MAXRS:  MAXMUM NUMBER OF RESIDUES
C  MAXSS:  MAXMUM NUMBER OF S-S CROSSLINK
C  MXRS1:  MAXRS+1
C  MXRS10: MAXRS*10
C  MAXLEN: ARRAY SIZE OF INTER IN PREP IN PRECEP ?
C  MAXDBL: MAXMUM NUMBER OF DIPOLES (?)
C  MWORK:  MAXIMUM SIZE OF REAL WORK ARRAY
C  MIWORK: MAXIMUM SIZE OF INTEGER WORK ARRAY
C  MCWORK: MAXIMUM SIZE OF CHARACTER WORK ARRAY
CMSP  INCLUDE (COMMAND)
C COMMAND.CMN
C
C PURPOSE : COMMON BLOCKS FOR PARSER
C
      COMMON/COMMAN /COMLYN(2000)
      COMMON/COMMSI  /COMLEN,MXCMSZ
      CHARACTER*1 COMLYN
      INTEGER COMLEN
      EQUIVALENCE (COMLYN(1),COMLY2 )
      CHARACTER*2000 COMLY2
C
C     COMLYN  - STORES CHARACTERS IN INPUT (COMMAND) LINE, UP TO 2000
C               CHARACTERS
C     COMLEN  - ACTUAL NUMBER OF NON-BLANK CHARACTERS
C     MXCMSZ  - MAX NUMBER OF CHARACTERS = 2000
C     COMLYN2 - A CHARACTER*2000 REPRESENTATION OF THE COMMAND LINE
C
CMSP  INCLUDE (ALPHA)
C ALPHA
C
      CHARACTER*4  ATNAME,RENAME
      CHARACTER*80 TITLE
      COMMON/ALPHA1/ATNAME(MAXATM),RENAME(MAXATM)
      COMMON/ALPHA2/NMBRES(MAXATM)
      COMMON/TITLE/TITLE
C
C  ATNAME:   ATOM NAMES (ECEPP ORDER)
C  RENAME :   RESIDUE NAMES (ECEPP ORDER)
C  NMBRES :   RESIDUE NUMBER (NORMAL NUMBERING)
C  TITLE  :   TITLE OF PRECEP
C
CMSP  INCLUDE (UNITNUMS)
C  UNITNUMS.CMN
C
C  THIS FILE CONTAINS THE  COMMON BLOCK NECESSARY
C  TO ASSIGN ALL I/0 UNIT NUMBERS. A SUMMARY OF ALL I/O FILES USED BY
C  IMPACT APPEARS BELOW, ORGANIZED BY TASK.
C
C
      COMMON/UNITNU  /IN1,IN2,IN3,IN4,IFN4,
     *               IOUT1,IOUT2,IOUT3,
     * IN01,IOUT02,IOUT06,
C
C PREIN
C
     * IN11,IN13,IOUT12,IOUT14,IOUT16,IN15,IN17,IOUT18,IN19,IOUT20,
C
C PRECEP
C
     * IN21,IN23,IN25,IN27,IN29,
     * IOUT22,IOUT24,IOUT26,IOUT28,IOUT30,
C
C MINIMIZATION
C
     * IN31,IN33,IN35,IN37,IN39,
     * IOUT32,IOUT34,IOUT36,IOUT38,IOUT39,IOUT40,
C
C NORMAL MODE
C
     * IN41,IN43,IN45,IN47,IN49,
     * IOUT42,IOUT44,IOUT46,IOUT48,IOUT50,IOUT52,IOUT54,IOUT56,IOUT58,
     * IOUT60,IOUT62,IOUT64,IOUT66,
C
C MONTE CARLO
C
     * IN71,IN73,IN75,IN77,IN79,
     * IOUT72,IOUT74,IOUT76,IOUT78
C
C PRIMARY INPUT FILE ----- IN01
C PRIMARY OUTPUT FILE ---- IOUT02
C PRIMARY LOG FILE ------- IOUT06
C
C ODD NUMBERS ARE RESERVED FOR INPUT,
C EVEN NUMBERS ARE RESERVED FOR OUTPUT
C FOR EXPLICIT DEFINITIONS OF INPUT AND OUTPUT FILES, PLEASE SEE MAIN
CMSP  INCLUDE (PRIMRY)
C PRIMRY
C
       INTEGER LIST
       COMMON /PRIMRY/LIST(MAXRES)
C
C   LIST : AMINO ACID RESIDUE NUMBER
C
CMSP  INCLUDE (VARANG)
C VARANG
C
      COMMON/VARANG/ANGRAD(10,MAXRES),VAR(MAXVAR),INDXV(MAXVAR),
     >              ANGLES(10,MAXRES)
C
C  ANGRAD :  DIHEDRAL ANGLES IN ECCEP ORDER (RADIAN)
C  VAR:    DIHEDRAL ANGLES IN WAKO ORDER (RADIAN)
C  INDXV : INDVX=NNN*100+MMM (MMM:1-10)
C            NNN: RESIDUE NUMBER
C            MMM: DIHEDRAL ANGLE NUMBER IN THE RESIDUE(NNN) IN ECEPP
C                 ORDER
C  ANGLES: DIHEDRAL ANGLES IN ECEPP ORDER (DEGREE)
C          USED AS THE WORK]]
C
      CHARACTER*4 DAOP
      INTEGER NURES,IPRNT,SSPAIR(MAXSS,2),NURESV
      INTEGER RESNU(MAXRES),NUDA(MAXRES),DANU(MAXRES,10)
C
C     *** WRITE DATA TO PRECEP INPUT FILE ***
C
C     IOUT02=20
C
      WRITE(IOUT12,2000)TITLE
 2000 FORMAT(A80)
      WRITE(IOUT12,2001)NURES,IPRNT
 2001 FORMAT(I5,'    1',I5,'    6    6')
      WRITE(IOUT12,2002)(LIST(I),I=2,(NURES-1))
 2002 FORMAT(20I3)
      WRITE(IOUT12,2003)LIST(1),LIST(NURES)
 2003 FORMAT(2I3)
      IF(NUSS.NE.0)THEN
        WRITE(IOUT12,2004)NUSS
 2004   FORMAT('   -1',I5)
        WRITE(IOUT12,2005)((SSPAIR(I,J),J=1,2),I=1,NUSS)
 2005   FORMAT(16I5)
      ENDIF
      DO 10 I=1,NURES
        WRITE(IOUT12,2006)(ANGLES(J,I),J=1,10)
 2006   FORMAT(10F8.3)
   10 CONTINUE
      WRITE(IOUT12,2007)DAOP
 2007 FORMAT(A4)
      IF(DAOP.EQ.'SPEC')THEN
        DO 20 I=1,NURESV
          WRITE(IOUT12,2008)RESNU(I),NUDA(I),DANU(I,J)
 2008     FORMAT(16I5)
   20   CONTINUE
        WRITE(IOUT12,2009)
 2009   FORMAT('    0')
      ENDIF
C
      RETURN
      END
