module gro
  implicit none

  type GRO_Atom
     integer res_serial, atm_serial
     character(5) res_name
     character(5) atm_name

     real x, y, z
     real vx, vy, vz

  end type GRO_Atom

! write_GRO <- To write output coordinates in gro format.
! read_GRO  <- To read inout coordinate in gro format.

contains

  subroutine write_GRO (unitnum, GA, N, boxsize_x, boxsize_y, boxsize_z)

    implicit none
    type (GRO_atom),allocatable,dimension(:),intent(in) :: GA
    integer, intent(in) :: unitnum
    integer, intent(in) :: N
    real, intent(in) :: boxsize_x, boxsize_y, boxsize_z

    integer i

    write(unitnum,'("generated by pdb2gro")')
    write(unitnum,'(I20)'), N
    do i = 1,N
       write(unitnum,'(I5,2A5,I5,3F8.3)'),&
            GA(i)%res_serial,GA(i)%res_name,trim(adjustl(GA(i)%atm_name)),GA(i)%atm_serial,&
            GA(i)%x,GA(i)%y,GA(i)%z
    end do
    write(unitnum,'(F13.8,1X,F13.8,1X,F13.8)'),boxsize_x, boxsize_y, boxsize_z
  end subroutine write_GRO

  subroutine read_GRO (unitnum, GA, N, boxsize_x, boxsize_y, boxsize_z)
    implicit none
    integer, intent(in) :: unitnum
    type (GRO_atom),allocatable,dimension(:),intent(inout) :: GA
    integer, intent(out) :: N
    real, intent(out) :: boxsize_x, boxsize_y, boxsize_z
    
    character(100) name
    type (GRO_atom),allocatable,dimension(:) :: A
    
    integer i, j

    read(unitnum,'()')
    read(unitnum,'(I20)'), N

    i = 1
    allocate(GA(i))
    do while ( i <= N )
       read(unitnum,'(I5,2A5,I5,3F8.3)'),&
            GA(i)%res_serial,GA(i)%res_name,GA(i)%atm_name,GA(i)%atm_serial,&
            GA(i)%x,GA(i)%y,GA(i)%z

!       print *, i

       allocate(A(i))
!       A = GA

       do j = 1,i
          A(j)%res_serial = GA(j)%res_serial
          A(j)%res_name = GA(j)%res_name 
          A(j)%atm_name = GA(j)%atm_name
          A(j)%atm_serial = GA(j)%atm_serial
          A(j)%x = GA(j)%x
          A(j)%y = GA(j)%y
          A(j)%z = GA(j)%z
       end do

       deallocate(GA)
       i = i + 1
       allocate(GA(i))
!       GA = A

       do j = 1,i
          GA(j)%res_serial = A(j)%res_serial
          GA(j)%res_name = A(j)%res_name 
          GA(j)%atm_name = A(j)%atm_name
          GA(j)%atm_serial = A(j)%atm_serial
          GA(j)%x = A(j)%x
          GA(j)%y = A(j)%y
          GA(j)%z = A(j)%z
       end do

       deallocate(A)
    end do
!    read(unitnum,'(F13.8,1X,F13.8,1X,F13.8)'),boxsize_x, boxsize_y, boxsize_z
  end subroutine read_GRO

end module gro
