#!/bin/sh

dirbase=$CASP/PATH/ADMCMC/
###########################
beta=030
delta=1.00
numstep=100000
interval=100
###########################
ref1=$CASP/ADv_C7eq.crd
ref2=$CASP/ADv_C7ax.crd
crd=$CASP/ADv_C7eq.crd
top=$CASP/ADv.top
##########################
dirinipath=${dirbase}/C7eq_C7ax_fC7eq_inipath
inipathnc=ADv_out_inipath.nc
##########################
dirinipathanl={dirbase}/C7eq_C7ax_fC7eq_inipath/anl
inipathene=
inipathdihed=
inipathrmsdf1=
inipathrmsdf2=
##########################
inipathnamebase=
modpathnamebase=
dirmodfpath=
##########################
fconst=100.0
dirsam=
dirsaminp=
dirsamcene=
dirsamfene=
dirsampmf=
dirsamanl=
crdforsam=
samncbase=
inpfilname=
##########################
