#include "copyright.i"

!*******************************************************************************
!
!
! Description:
!          CHARMM FORCE FIELD SUPPORT MODULE
!
! This is the CHARMM module which is used to provide
! support for the CHARMM force field within AMBER.
! This contains support for CHARMM specifics such as
! Urey-Bradley, CHARMM impropers and CMAP
!
! It is designed to be used with a special CHARMM prmtop
! file generated by chamber.
!
! Chamber Authors: Mike Crowley (NREL)
!                  Mark Williamson (SDSC)
!                  Ross Walker (SDSC)
!
! CHARMM Module Authors: Mark Williamson (SDSC)
!                        Ross Walker (SDSC)
!
! Date: Apr 2009.
!
!---------------------------------------------------------

!
!*******************************************************************************

!module charmm_gold_mod


subroutine pme_charmm_dump_gold(atm_cnt,frc,pot_ene)
!Dump all energies and atom forces in the same format
!with as c36a2's CHARMM frcdump command:

!  open unit 20 form write name "triala_forces.dat"
!  frcdump unit 20
!  close unit 20

!The purpose of this is to enable direct comparision to the
!CHARMM binary output.

  use pme_force_mod, only : pme_pot_ene_rec
  implicit none

  integer :: gold_file=42

  integer, intent(in)              :: atm_cnt
  double precision, intent(in)     :: frc(3, atm_cnt)
  type(pme_pot_ene_rec), intent(in) :: pot_ene


  integer :: i
  character(len=15),parameter  :: fmt = "(a6,d26.16)"

  open (unit = 42, file = "charmm_gold")

  write(gold_file,'(a5,i12)') "NATOM",atm_cnt
  write(gold_file,'(a6)') "ENERGY"
  write(gold_file,fmt) "ENER", pot_ene%total
  write(gold_file,fmt) "BOND", pot_ene%bond
  write(gold_file,fmt) "ANGL", pot_ene%angle
  write(gold_file,fmt) "UREY", pot_ene%angle_ub
  write(gold_file,fmt) "DIHE", pot_ene%dihedral
  write(gold_file,fmt) "IMPR", pot_ene%imp
  write(gold_file,fmt) "VDW ", pot_ene%vdw_tot + pot_ene%vdw_14
  write(gold_file,fmt) "ELEC", pot_ene%elec_tot + pot_ene%elec_14
  write(gold_file,fmt) "CMAP", pot_ene%cmap

  write(gold_file,'(a5)') "FORCE"
  do i=1, atm_cnt
    write(gold_file,'(i10,3(D26.16))') i,-frc(1,i),-frc(2,i),-frc(3,i)
  enddo

  close(gold_file)

end subroutine pme_charmm_dump_gold

subroutine gb_charmm_dump_gold(atm_cnt,frc,pot_ene)
!Dump all energies and atom forces in the same format
!with as c36a2's CHARMM frcdump command:

!  open unit 20 form write name "triala_forces.dat"
!  frcdump unit 20
!  close unit 20

!The purpose of this is to enable direct comparision to the
!CHARMM binary output.

  use gb_force_mod, only : gb_pot_ene_rec
  implicit none

  integer :: gold_file=42

  integer, intent(in)              :: atm_cnt
  double precision, intent(in)     :: frc(3, atm_cnt)
  type(gb_pot_ene_rec), intent(in) :: pot_ene


  integer :: i
  character(len=15),parameter  :: fmt = "(a6,d26.16)"

  open (unit = 42, file = "charmm_gold")

  write(gold_file,'(a5,i12)') "NATOM",atm_cnt
  write(gold_file,'(a6)') "ENERGY"
  write(gold_file,fmt) "ENER", pot_ene%total
  write(gold_file,fmt) "BOND", pot_ene%bond
  write(gold_file,fmt) "ANGL", pot_ene%angle
  write(gold_file,fmt) "UREY", pot_ene%angle_ub
  write(gold_file,fmt) "DIHE", pot_ene%dihedral
  write(gold_file,fmt) "IMPR", pot_ene%imp
  write(gold_file,fmt) "VDW ", pot_ene%vdw_tot + pot_ene%vdw_14
  write(gold_file,fmt) "ELEC", pot_ene%elec_tot + pot_ene%elec_14
  write(gold_file,fmt) "CMAP", pot_ene%cmap

  write(gold_file,'(a5)') "FORCE"
  do i=1, atm_cnt
    write(gold_file,'(i10,3(D26.16))') i,-frc(1,i),-frc(2,i),-frc(3,i)
  enddo

  close(gold_file)

end subroutine gb_charmm_dump_gold

!end module charmm_gold_mod
