#ifdef CLINK_CAPS
#define gpu_get_device_info_       GPU_GET_DEVICE_INFO
#define gpu_get_memory_info_       GPU_GET_MEMORY_INFO
#define gpu_setup_system_          GPU_SETUP_SYSTEM
#define gpu_upload_crd_            GPU_UPLOAD_CRD
#define gpu_download_crd_          GPU_DOWNLOAD_CRD
#define gpu_upload_charges_        GPU_UPLOAD_CHARGES
#define gpu_download_charges_      GPU_DOWNLOAD_CHARGES
#define gpu_upload_sigeps_         GPU_UPLOAD_SIGEPS
#define gpu_download_sigeps_       GPU_DOWNLOAD_SIGEPS
#define gpu_upload_fs_             GPU_UPLOAD_FS
#define gpu_download_fs_           GPU_DOWNLOAD_FS
#define gpu_upload_rborn_          GPU_UPLOAD_RBORN
#define gpu_download_rborn_        GPU_DOWNLOAD_RBORN
#define gpu_upload_masses_         GPU_UPLOAD_MASSES
#define gpu_download_masses_       GPU_DOWNLOAD_MASSES
#define gpu_upload_reff_           GPU_UPLOAD_REFF
#define gpu_download_reff_         GPU_DOWNLOAD_REFF
#define gpu_upload_frc_            GPU_UPLOAD_FRC
#define gpu_download_frc_          GPU_DOWNLOAD_FRC
#define gpu_upload_vel_            GPU_UPLOAD_VEL
#define gpu_download_vel_          GPU_DOWNLOAD_VEL
#define gpu_upload_last_vel_       GPU_UPLOAD_LAST_VEL
#define gpu_download_last_vel_     GPU_DOWNLOAD_LAST_VEL
#define gpu_bonds_setup_           GPU_BONDS_SETUP
#define gpu_angles_setup_          GPU_ANGLES_SETUP
#define gpu_dihedrals_setup_       GPU_DIHEDRALS_SETUP
#define gpu_nb14_setup_            GPU_NB14_SETUP
#define gpu_constraints_setup_     GPU_CONSTRAINTS_SETUP
#define gpu_angles_ub_setup_       GPU_ANGLES_UB_SETUP
#define gpu_dihedrals_imp_setup_   GPU_DIHEDRALS_IMP_SETUP
#define gpu_cmap_setup_            GPU_CMAP_SETUP
#define gpu_shake_setup_           GPU_SHAKE_SETUP
#define gpu_get_water_distances_   GPU_GET_WATER_DISTANCES
#define gpu_create_outputbuffers_  GPU_CREATE_OUTPUTBUFFERS
#define gpu_init_pbc_              GPU_INIT_PBC
#define gpu_neighbor_list_setup_   GPU_NEIGHBOR_LIST_SETUP
#define gpu_skin_test_             GPU_SKIN_TEST
#define gpu_molecule_list_setup_   GPU_MOLECULE_LIST_SETUP
#define gpu_constraint_molecule_list_setup_   GPU_CONSTRAINT_MOLECULE_LIST_SETUP
#define gpu_pme_ntp_setup_         GPU_PME_NTP_SETUP
#define gpu_pme_alltasks_setup_    GPU_PME_ALLTASKS_SETUP
#define gpu_get_self              GPU_GET_SELF
#define gpu_get_grid_weights_      GPU_GET_GRID_WEIGHTS
#define gpu_fill_charge_grid_      GPU_FILL_CHARGE_GRID
#define gpu_fft3drc_forward_       GPU_FFT3DRC_FORWARD
#define gpu_scalar_sumrc_          GPU_SCALAR_SUMRC
#define gpu_fft3drc_back_          GPU_FFT3DRC_BACK
#define gpu_grad_sum_              GPU_GRAD_SUM
#define gpu_self_                  GPU_SELF
#define gpu_vdw_correction_        GPU_VDW_CORRECTION
#define gpu_pme_ene_               GPU_PME_ENE
#define gpu_pme_force_             GPU_PME_FORCE
#define gpu_pressure_scale_        GPU_PRESSURE_SCALE
#define gpu_final_gb_setup_        GPU_FINAL_GB_SETUP
#define gpu_build_threadblock_work_list_        GPU_BUILD_THREADBLOCK_WORK_LIST
#define gpu_final_setup_           GPU_FINAL_SETUP
#define gpu_update_                GPU_UPDATE
#define gpu_shake_                 GPU_SHAKE
#define gpu_recalculate_velocities_  GPU_RECALCULATE_VELOCITIES
#define gpu_scale_velocities_      GPU_SCALE_VELOCITIES
#define gpu_calculate_kinetic_energy_ GPU_CALCULATE_KINETIC_ENERGY
#define gpu_recenter_molecule_     GPU_RECENTER_MOLECULE
#define gpu_amrset_                GPU_AMRSET
#define gpu_dump_float_            GPU_DUMP_FLOAT
#define gpu_dump_grid_weights_     GPU_DUMP_GRID_WEIGHTS
#define gpu_dump_img_double_vector_ GPU_DUMP_IMG_DOUBLE_VECTOR
#define gpu_dump_img_int_vector_   GPU_DUMP_IMG_INT_VECTOR
#define gpu_dump_complex_grid_     GPU_DUMP_COMPLEX_GRID
#define gpu_load_complex_grid_     GPU_LOAD_COMPLEX_GRID
#define gpu_dump_grid_             GPU_DUMP_GRID
#define gpu_dump_int_vector_       GPU_DUMP_INT_VECTOR
#define gpu_dump_mapped_int_vector_       GPU_DUMP_MAPPED_INT_VECTOR
#define gpu_dump_mapped_double_vector_ GPU_DUMP_MAPPED_DOUBLE_VECTOR
#define gpu_dump_int_              GPU_DUMP_INT
#define gpu_dump_double_           GPU_DUMP_DOUBLE
#define gpu_dump_double_vector_    GPU_DUMP_DOUBLE_VECTOR
#define gpu_dump_dval_             GPU_DUMP_DVAL
#define gpu_gb_ene_                GPU_GB_ENE
#define gpu_clear_forces_          GPU_CLEAR_FORCES
#define gpu_gb_forces_             GPU_GB_FORCES
#define gpu_get_nb_energy_         GPU_GET_NB_ENERGY
#define gpu_startup_               GPU_STARTUP
#define gpu_set_device_            GPU_SET_DEVICE
#define gpu_init_                  GPU_INIT
#define gpu_shutdown_              GPU_SHUTDOWN
#define gpu_get_slave_device_info_ GPU_GET_SLAVE_DEVICE_INFO
#define gpu_send_slave_device_info_ GPU_SEND_SLAVE_DEVICE_INFO
#define gpu_ips_setup_             GPU_IPS_SETUP
#define gpu_ips_update_            GPU_IPS_UPDATE
#define gpu_ips_ene_               GPU_IPS_ENE
#define gpu_ips_force_             GPU_IPS_FORCE
#define gpu_ntp_setup_             GPU_NTP_SETUP
#define gpu_vrand_reset_velocities_ GPU_VRAND_RESET_VELOCITIES
#define gpu_local_to_global_       GPU_LOCAL_TO_GLOBAL
#define gpu_init_extra_pnts_nb14_  GPU_INIT_EXTRA_PNTS_NB14
#define gpu_gather_pme_forces_     GPU_GATHER_PME_FORCES
#define gpu_gather_ips_forces_     GPU_GATHER_IPS_FORCES
#define gpu_gb_igb8_setup_         GPU_GB_IGB8_SETUP

#else
#ifdef NO_C_UNDERSCORE
#define gpu_get_device_info_       gpu_get_device_info
#define gpu_get_memory_info_       gpu_get_memory_info
#define gpu_setup_system_          gpu_setup_system
#define gpu_upload_crd_			   gpu_upload_crd
#define gpu_download_crd_		   gpu_download_crd
#define gpu_upload_charges_		   gpu_upload_charges
#define gpu_download_charges_	   gpu_download_charges
#define gpu_upload_sigeps_	       gpu_upload_sigeps
#define gpu_download_sigeps_	   gpu_download_sigeps
#define gpu_upload_fs_	           gpu_upload_fs
#define gpu_download_fs_	       gpu_download_fs
#define gpu_upload_rborn_	       gpu_upload_rborn
#define gpu_download_rborn_	       gpu_download_rborn
#define gpu_upload_masses_	       gpu_upload_masses
#define gpu_download_masses_	   gpu_download_masses
#define gpu_upload_reff_	       gpu_upload_reff
#define gpu_download_reff_	       gpu_download_reff
#define gpu_upload_frc_	           gpu_upload_frc
#define gpu_download_frc_	       gpu_download_frc
#define gpu_upload_vel_	           gpu_upload_vel
#define gpu_download_vel_	       gpu_download_vel
#define gpu_upload_last_vel_	   gpu_upload_last_vel
#define gpu_download_last_vel_	   gpu_download_last_vel
#define gpu_bonds_setup_	       gpu_bonds_setup
#define gpu_angles_setup_	       gpu_angles_setup
#define gpu_dihedrals_setup_	   gpu_dihedrals_setup
#define gpu_nb14_setup_	           gpu_nb14_setup
#define gpu_constraints_setup_	   gpu_constraints_setup
#define gpu_angles_ub_setup_	   gpu_angles_ub_setup
#define gpu_dihedrals_imp_setup_   gpu_dihedrals_imp_setup
#define gpu_cmap_setup_            gpu_cmap_setup
#define gpu_shake_setup_           gpu_shake_setup
#define gpu_get_water_distances_   gpu_get_water_distances
#define gpu_create_outputbuffers_  gpu_create_outputbuffers
#define gpu_init_pbc_              gpu_init_pbc
#define gpu_neighbor_list_setup_   gpu_neighbor_list_setup
#define gpu_skin_test_             gpu_skin_test
#define gpu_molecule_list_setup_   gpu_molecule_list_setup
#define gpu_constraint_molecule_list_setup_   gpu_constraint_molecule_list_setup
#define gpu_pme_ntp_setup_         gpu_pme_ntp_setup
#define gpu_pme_alltasks_setup_    gpu_pme_alltasks_setup
#define gpu_get_self              gpu_get_self
#define gpu_get_grid_weights_      gpu_get_grid_weights
#define gpu_fill_charge_grid_      gpu_fill_charge_grid
#define gpu_fft3drc_forward_       gpu_fft3drc_forward
#define gpu_scalar_sumrc_          gpu_scalar_sumrc
#define gpu_fft3drc_back_          gpu_fft3drc_back
#define gpu_grad_sum_              gpu_grad_sum
#define gpu_self_                  gpu_self
#define gpu_vdw_correction_        gpu_vdw_correction
#define gpu_pme_ene_               gpu_pme_ene
#define gpu_pme_force_             gpu_pme_force
#define gpu_pressure_scale_        gpu_pressure_scale
#define gpu_final_gb_setup_        gpu_final_gb_setup
#define gpu_build_threadblock_work_list_        gpu_build_threadblock_work_list
#define gpu_final_setup_           gpu_final_setup
#define gpu_update_                gpu_update
#define gpu_shake_                 gpu_shake
#define gpu_recalculate_velocities_                 gpu_recalculate_velocities
#define gpu_scale_velocities_      gpu_scale_velocities
#define gpu_calculate_kinetic_energy_      gpu_calculate_kinetic_energy
#define gpu_recenter_molecule_     gpu_recenter_molecule
#define gpu_amrset_                gpu_amrset
#define gpu_dump_float_            gpu_dump_float
#define gpu_dump_grid_weights_     gpu_dump_grid_weights
#define gpu_dump_img_double_vector_     gpu_dump_img_double_vector
#define gpu_dump_img_int_vector_   gpu_dump_img_int_vector
#define gpu_dump_complex_grid_     gpu_dump_complex_grid
#define gpu_load_complex_grid_     gpu_load_complex_grid
#define gpu_dump_grid_             gpu_dump_grid
#define gpu_dump_int_vector_       gpu_dump_int_vector
#define gpu_dump_mapped_int_vector_       gpu_dump_mapped_int_vector
#define gpu_dump_mapped_double_vector_       gpu_dump_mapped_double_vector
#define gpu_dump_int_              gpu_dump_int
#define gpu_dump_double_           gpu_dump_double
#define gpu_dump_double_vector_    gpu_dump_double_vector
#define gpu_dump_dval_             gpu_dump_dval
#define gpu_gb_ene_                gpu_gb_ene
#define gpu_clear_forces_          gpu_clear_forces
#define gpu_gb_forces_             gpu_gb_forces
#define gpu_get_nb_energy_         gpu_get_nb_energy
#define gpu_startup_               gpu_startup
#define gpu_set_device_            gpu_set_device
#define gpu_init_                  gpu_init
#define gpu_shutdown_              gpu_shutdown
#define gpu_get_slave_device_info_ gpu_get_slave_device_info
#define gpu_send_slave_device_info_ gpu_send_slave_device_info
#define gpu_ips_setup_             gpu_ips_setup
#define gpu_ips_update_            gpu_ips_update
#define gpu_ips_ene_               gpu_ips_ene
#define gpu_ips_force_             gpu_ips_force
#define gpu_ntp_setup_             gpu_ntp_setup
#define gpu_vrand_reset_velocities_ gpu_vrand_reset_velocities
#define gpu_local_to_global_       gpu_local_to_global
#define gpu_init_extra_pnts_nb14_  gpu_init_extra_pnts_nb14
#define gpu_gather_pme_forces_     gpu_gather_pme_forces
#define gpu_gather_ips_forces_     gpu_gather_ips_forces
#define gpu_gb_igb8_setup_         gpu_gb_igb8_setup_

#else
#ifdef DBL_C_UNDERSCORE
#define gpu_get_device_info_       gpu_get_device_info__
#define gpu_get_memory_info_       gpu_get_memory_info__
#define gpu_setup_system_          gpu_setup_system__
#define gpu_upload_crd_			   gpu_upload_crd__
#define gpu_download_crd_		   gpu_download_crd__
#define gpu_upload_charges_		   gpu_upload_charges__
#define gpu_download_charges_	   gpu_download_charges__
#define gpu_upload_sigeps_	       gpu_upload_sigeps__
#define gpu_download_sigeps_	   gpu_download_sigeps__
#define gpu_upload_fs_	           gpu_upload_fs__
#define gpu_download_fs_	       gpu_download_fs__
#define gpu_upload_rborn_	       gpu_upload_rborn__
#define gpu_download_rborn_	       gpu_download_rborn__
#define gpu_upload_masses_	       gpu_upload_masses__
#define gpu_download_masses_	   gpu_download_masses__
#define gpu_upload_reff_	       gpu_upload_reff__
#define gpu_download_reff_	       gpu_download_reff__
#define gpu_upload_frc_	           gpu_upload_frc__
#define gpu_download_frc_	       gpu_download_frc__
#define gpu_upload_vel_	           gpu_upload_vel__
#define gpu_download_vel_	       gpu_download_vel__
#define gpu_upload_last_vel_	   gpu_upload_last_vel__
#define gpu_download_last_vel_	   gpu_download_last_vel__
#define gpu_bonds_setup_	       gpu_bonds_setup__
#define gpu_angles_setup_	       gpu_angles_setup__
#define gpu_dihedrals_setup_	   gpu_dihedrals_setup__
#define gpu_nb14_setup_	           gpu_nb14_setup__
#define gpu_constraints_setup_	   gpu_constraints_setup__
#define gpu_angles_ub_setup_	   gpu_angles_ub_setup__
#define gpu_dihedrals_imp_setup_   gpu_dihedrals_imp_setup__
#define gpu_cmap_setup_            gpu_cmap_setup__
#define gpu_shake_setup_           gpu_shake_setup__
#define gpu_get_water_distances_   gpu_get_water_distances__
#define gpu_create_outputbuffers_  gpu_create_outputbuffers__
#define gpu_init_pbc_              gpu_init_pbc__
#define gpu_neighbor_list_setup_   gpu_neighbor_list_setup__
#define gpu_skin_test_             gpu_skin_test__
#define gpu_molecule_list_setup_   gpu_molecule_list_setup__
#define gpu_constraint_molecule_list_setup_   gpu_constraint_molecule_list_setup__
#define gpu_pme_ntp_setup_         gpu_pme_ntp_setup__
#define gpu_pme_alltasks_setup_    gpu_pme_alltasks_setup__
#define gpu_get_self              gpu_get_self__
#define gpu_get_grid_weights_      gpu_get_grid_weights__
#define gpu_fill_charge_grid_      gpu_fill_charge_grid__
#define gpu_fft3drc_forward_       gpu_fft3drc_forward__
#define gpu_scalar_sumrc_          gpu_scalar_sumrc__
#define gpu_fft3drc_back_          gpu_fft3drc_back__
#define gpu_grad_sum_              gpu_grad_sum__
#define gpu_self_                  gpu_self__
#define gpu_vdw_correction_        gpu_vdw_correction__
#define gpu_pme_ene_               gpu_pme_ene__
#define gpu_pme_force_             gpu_pme_force__
#define gpu_pressure_scale_        gpu_pressure_scale__
#define gpu_final_gb_setup_        gpu_final_gb_setup__
#define gpu_build_threadblock_work_list_        gpu_build_threadblock_work_list__
#define gpu_final_setup_           gpu_final_setup__
#define gpu_update_                gpu_update__
#define gpu_shake_                 gpu_shake__
#define gpu_recalculate_velocities_                 gpu_recalculate_velocities__
#define gpu_scale_velocities_      gpu_scale_velocities__
#define gpu_calculate_kinetic_energy_      gpu_calculate_kinetic_energy__
#define gpu_recenter_molecule_     gpu_recenter_molecule__
#define gpu_amrset_                gpu_amrset__
#define gpu_dump_float_            gpu_dump_float__
#define gpu_dump_grid_weights_     gpu_dump_grid_weights__
#define gpu_dump_img_double_vector_     gpu_dump_img_double_vector__
#define gpu_dump_img_int_vector_   gpu_dump_img_int_vector__
#define gpu_dump_complex_grid_     gpu_dump_complex_grid__
#define gpu_load_complex_grid_     gpu_load_complex_grid__
#define gpu_dump_grid_             gpu_dump_grid__
#define gpu_dump_int_vector_       gpu_dump_int_vector__
#define gpu_dump_mapped_int_vector_       gpu_dump_mapped_int_vector__
#define gpu_dump_mapped_double_vector_       gpu_dump_mapped_double_vector__
#define gpu_dump_int_              gpu_dump_int__
#define gpu_dump_double_           gpu_dump_double__
#define gpu_dump_double_vector_    gpu_dump_double_vector__
#define gpu_dump_dval_             gpu_dump_dval__
#define gpu_gb_ene_                gpu_gb_ene__
#define gpu_clear_forces_          gpu_clear_forces__
#define gpu_gb_forces_             gpu_gb_forces__
#define gpu_get_nb_energy_         gpu_get_nb_energy__
#define gpu_startup_               gpu_startup__
#define gpu_set_device_            gpu_set_device__
#define gpu_init_                  gpu_init__
#define gpu_shutdown_              gpu_shutdown__
#define gpu_get_slave_device_info_ gpu_get_slave_device_info__
#define gpu_send_slave_device_info_ gpu_send_slave_device_info__
#define gpu_ips_setup_             gpu_ips_setup__
#define gpu_ips_update_            gpu_ips_update__
#define gpu_ips_ene_               gpu_ips_ene__
#define gpu_ips_force_             gpu_ips_force__
#define gpu_ntp_setup_             gpu_ntp_setup__
#define gpu_vrand_reset_velocities_ gpu_vrand_reset_velocities__
#define gpu_local_to_global_       gpu_local_to_global__
#define gpu_init_extra_pnts_nb14_  gpu_init_extra_pnts_nb14__
#define gpu_gather_pme_forces_     gpu_gather_pme_forces__
#define gpu_gather_ips_forces_     gpu_gather_ips_forces__
#define gpu_gb_igb8_setup_         gpu_gb_igb8_setup__

#else
// calling convention OK
#endif
#endif
#endif


#ifdef MPI
#ifdef CLINK_CAPS
#define gpu_gather_forces_       PROC_GPU_GATHER_FORCES
#else
#ifdef NO_C_UNDERSCORE
#define gpu_gather_forces_       proc_gpu_gather_forces
#else
#ifdef DBL_C_UNDERSCORE
#define gpu_gather_forces_       proc_gpu_gather_forces__
#else
// calling convention OK
#define gpu_gather_forces_       proc_gpu_gather_forces_
#endif
#endif
#endif
#endif

