C********************************************************************
C                                                                   *
C               SUPPLEMENTARY PROGRAMS                              *
C                                                                   *
C********************************************************************
      SUBROUTINE  PREP
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8  EES,ENB,ETOT
CMSP  INCLUDE (MAXSIZE)
      INCLUDE 'inc/maxsize'
CMSP  INCLUDE (SIZE)
      INCLUDE 'inc/size'
CMSP  INCLUDE (INTER0)
      INCLUDE 'inc/inter0'
CMSP  INCLUDE (UNITNUMS)
      INCLUDE 'inc/unitnums'
      COMMON/CALC/EES,ENB,ETOT,JM,JJ
      COMMON/CAL001/KSTRT,KFIN
C     COMMON/IOUNIT/JREAD
C     COMMON/PREPAR/LNUM,JMLAST,KMLAST,LNUMS,LEN,NATM
      COMMON/PREPAR/LNUM,JMLAST,KMLAST,LNUMS,LEN
C     COMMON/RUNS/INTER(3,MAXLEN)
C
C
      I4RUN=0 !CAK
      I5RUN=0 !CAK
      IOFF=0  !CAK
      IF (LEN.GT.MAXLEN)  THEN
        WRITE(6,700)
        STOP
      ENDIF
      ISKIP = JM-JMLAST-1
      JRUN = KFIN-KSTRT+1
      IF (LNUM.EQ.4)  GO TO  210
C
C THIS SECTION IS FOR 1-5'S
C
      IF (LNUMS.EQ.5)  GO TO  110
C
C THE LAST CALL WAS FROM CAL14
C
      IF (JM.NE.JMLAST)  GO TO  100
      I5RUN = JRUN
      NEXT = KMLAST+1
      IF (KSTRT.NE.NEXT)  GO TO  50
      RETURN
C
C THE CURRENT RUN OF 1-5'S DOES NOT FOLLOW CONSECUTIVELY THE RUN OF
C 1-4'S FOR THIS JM.
C
C 50  INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = 0
  50  INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = 0
      LEN = LEN+1
      IOFF = KSTRT-JM
      I4RUN = 0
      RETURN
C
C THERE ARE NO 1-5'S FOR THE PREVIOUS JM AND (SO FAR) NO 1-4'S FOR THE
C CURRENT JM.
C
  100 KEY = 0
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
      IOFF = 0
      I4RUN = 0
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
      GO TO  130
C
C THE LAST CALL WAS FROM CAL15
C
  110 IF (JM.NE.JMLAST)  GO TO  120
      KSKIP = KSTRT-KMLAST-1
      IF (KSKIP.GT.0)  GO TO  120
      I5RUN = I5RUN + JRUN
      RETURN
C
C THERE ARE NO 1-4'S FOR THE CURRENT ATOM JM
C OR 1-5'S FOR ATOM JM ARE NOT CONSECUTIVE.
C
  120 KEY = I5RUN
C     IF (KMLAST.EQ.NATM) KEY=JMLAST+IOFF+I4RUN-NATM-2
      IF (KMLAST.EQ.NUMATM) KEY=JMLAST+IOFF+I4RUN-NUMATM-2
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
C     IF (JM.NE.JMLAST.AND.KMLAST.NE.NATM)  THEN
      IF (JM.NE.JMLAST.AND.KMLAST.NE.NUMATM)  THEN
C       INTER(1,LEN) = 0
C       INTER(2,LEN) = 0
C       INTER(3,LEN) = 0
        INTATM(1,LEN) = 0
        INTATM(2,LEN) = 0
        INTATM(3,LEN) = 0
        LEN = LEN + 1
      ENDIF
  130 I4RUN = 0
      I5RUN = JRUN
      IOFF = KSTRT-JM
      RETURN
C
C THIS SECTION IS FOR 1-4'S
C
  210 IF (LNUMS.EQ.4)  GO TO  220
      IF (LNUMS.EQ.0)  GO TO  235
C
C THE LAST CALL WAS FROM CAL15 SO PRINT OFFSET, LENGTH OF RUN, KEY.
C
      KEY = I5RUN
C     IF (KMLAST.EQ.NATM) KEY=JMLAST+IOFF+I4RUN-NATM-2
      IF (KMLAST.EQ.NUMATM) KEY=JMLAST+IOFF+I4RUN-NUMATM-2
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
C
C     IF (ISKIP.EQ.0.AND.KMLAST.NE.NATM)  GO TO  240
      IF (ISKIP.EQ.0.AND.KMLAST.NE.NUMATM)  GO TO  240
      IF (ISKIP.LE.0)  GO TO  150
      DO  140  I = 1, ISKIP
C     INTER(1,LEN) = 0
C     INTER(2,LEN) = 0
C     INTER(3,LEN) = 0
      INTATM(1,LEN) = 0
      INTATM(2,LEN) = 0
      INTATM(3,LEN) = 0
      LEN = LEN + 1
  140 CONTINUE
  150 CONTINUE
C
      I4RUN = JRUN
      IOFF = KSTRT-JM
      RETURN
C
C THE LAST CALL WAS FROM CAL14
C
  220 KSUM = KMLAST+1
      IF (KSUM.NE.KSTRT)  GO TO  230
C
C THIS RUN FOLLOWS CONSECUTIVELY THE LAST 1-4 RUN
C
      I4RUN = I4RUN+JRUN
      RETURN
C
C THIS 1-4 RUN DOES NOT FOLLOW CONSECUTIVELY THE LAST 1-4 RUN.
C
  230 KEY = 0
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
      IF (JM.NE.JMLAST)  GO TO  240
  235 I4RUN = JRUN
      IOFF = KSTRT-JM
      RETURN
C
C THIS IS A NEW ATOM JM, AND THE LAST JM HAD A 1-4 RUN NOT
C FOLLOWED BY 1-5'S.
C
  240 I4RUN = 0
      IOFF = 0
      KEY = 0
C     INTER(1,LEN) = IOFF
C     INTER(2,LEN) = I4RUN
C     INTER(3,LEN) = KEY
      INTATM(1,LEN) = IOFF
      INTATM(2,LEN) = I4RUN
      INTATM(3,LEN) = KEY
      LEN = LEN + 1
      I4RUN = JRUN
      IOFF = KSTRT-JM
      RETURN
C
C
  700 FORMAT('0  **ERROR MESSAGE FROM THE SUBROUTINE PREP. ' /
     &  '    LEN HAS EXCEEDS MAXLEN.  ASSIGN A GREATER NUMBER TO',
     &  ' MAXLEN IN THE PARAMETER STATEMENTS AND TRY AGAIN.')
      END
